version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks: 
      - private
    mem_limit: "512m"
    cpus: "0.25" 

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: on-failure
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
      - postgres
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password 
    networks:
      - private
    mem_limit: "512m"
    cpus: "0.5"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "15432:80"
    networks:
        - private
        - public
  
  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - public
      - private
    mem_limit: "512m"
    cpus: "0.5"

  api-notification:
    image: api-notification
    build: ./api-notification
    container_name: api-notification
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - public
      - private
    mem_limit: "512m"
    cpus: "0.5" 

networks:
  public:
  private: